#!/bin/sh
#
# eth0          Starts eth0 with static IP
#

case "$1" in
  start)
        printf "Setting up eth0: "
        ifconfig eth0 up 192.168.2.21
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  stop)
        printf "Stopping eth0: "
        ifconfig eth0 down
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
